service: product-service

frameworkVersion: '2'
useDotenv: true


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: eu-west-1

  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
         path: products
         method: get
         cors: true
  addProduct:
    handler: handler.addProduct
    events:
      - http:
         path: products
         method: post
         cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
