service: authorization-service

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: eu-west-1

  environment:
    handleman: ${env:handleman}
    
  iamRoleStatements:

resources:
  Resources:

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
