service: import-service

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: eu-west-1

  environment:
    SQS_URL:
      Ref: SQSQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::aws-fe-shop-import"
    - Effect: "Allow"
      Action: "s3:getObject"
      Resource:
        - "arn:aws:s3:::aws-fe-shop-import"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::aws-fe-shop-import/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [SQSQueue, Arn]

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue

# arn:aws:s3:::aws-fe-shop-import
functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
         path: import
         method: get
         cors: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: aws-fe-shop-import
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
